name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Run tests
        run: dotnet test --verbosity normal

      - name: Build
        run: dotnet build --no-restore --configuration Release --verbosity minimal
